### ISSUE TITLE
用例子启动微信小程序 Input 组件获取不了值

### ISSUE THREAD

**Issue by Tenodec** [remaxjs/examples#14]
VM6374:1 Warning: Encountered two children with the same key, `%s`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version.%s 4 
    in checkbox-group (created by ForwardRef(Component))
    in ForwardRef(Component) (created by IndexPage)
    in view (created by ForwardRef(Component))
    in ForwardRef(Component) (created by IndexPage)
    in view (created by ForwardRef(Component))
    in ForwardRef(Component) (created by IndexPage)
    in IndexPage (created by ConnectFunction)
    in ConnectFunction (created by PageWrapper)
    in PageWrapper
    in Provider (created by _App)
    in _App

**Comment by Darmody** [comment]
请问微信调试器的版本是？

**Comment by yesmeck** [comment]
麻烦把  issue 提到 https://github.com/remaxjs/remax/issues
